import codecs
import sys
import re
import os 

import gflags
FLAGS = gflags.FLAGS
gflags.DEFINE_string("w2vdict", None, "dict file generated by google word2vec")
gflags.DEFINE_integer("outname", None, "output vocab name")


gflags.MarkFlagAsRequired('w2vdict') 
gflags.MarkFlagAsRequired('topn') 

try:
	FLAGS(sys.argv)
except gflags.FlagsError as e:
	print "\n%s" % e 
	print FLAGS.GetHelp(include_special_flags=False) 
	sys.exit(1)


filename = FLAGS.w2vdict 
outname = FLAGS.outname
vocab = [
    "_PAD",
    "_GO",
    "_EOS",
    "_UNK"
]
with codecs.open(filename) as f:
    for line in f: 
        segs = re.split("[\t ]+", line.strip())
        if segs[0] == "</s>":
            continue
        vocab.append(segs[0].strip())

with codecs.open(outname, "w") as f:
    for each in vocab:
        f.write("%s\n" % each)
        



